# .travis.yml
language: node_js   #前端工程所以是JavaScript，编译环境是node_js
node_js:
  - '15.12.0'   #指定node版本
branchs:
  only:
  - master  #指定只有检测到master分支有变动时才执行任务

cache:
  directories:
    - node_modules

env:
  global:
    -GH_REF: github.com/1017206511/yzq-blog.git
    -secure: "b3Xb6cOUUjr2SfaYo3Ezmsb+YQcwrkcy6/l+4VEZ5N/t6dVPt+RyYr8h+VqQUXkGCWuye4OqLEYED/sPYRgeFG4ZfL6PQFm+iEeefXUvVIvHGzjPuUm7OvvAm9H/lBLDw7kfoesLKjMHQwLVXD9noiEzraaXZ8a8Dj5jBF6BIzp8hVAv+Em5FZ28VuEuXB9S4mB9wpxHFiuFCWeExO9Kc/ep50Zsi5fyrfrRrJD5F9ClOcCP9pPhEstwi6g+en2hCS2vN122rKx7AzlhE8YfUn1xKVAM3SWbMQE5WjL/bNfFmVG6HLnBdIvromXMgsOBqAR5zZrjHzMlN4J/FfV7AC9T1LMwGL7Adkur/Dpi1ngkosTN+t+WwHg43navifujgu1UOI32Tolb8hQDF4bqhIEcOskTjY5ssVUF/urE+RHkfHc8zwVGjD0/7gdBfprNWNG3/U7Ei+/1gekFYsVtW3ogwygG4f3vwg0iCTSM0smVp9lZR9wNRUyfhDivIaQxDXUb7YxBVm6Os74gJuQiWHlwZ+pDdOaMpMSEfXzlXMdxCJGNIZT5jzV+YzWC0no0r3WeIJn4GUmRgL648i+csVZv89E/V9QzccgB7z355MA8CS9heRvmmYB6BG+euD0S7SE139YpX+70SPBTVLG7X5uXiaCcvMmjs4HNVfcC0ZE="
# 配置环境
before_install:
  # 配置 ssh
  - cp .travis/ssh_config ~/.ssh/config
  - cp .travis/id_rsa.pub ~/.ssh/id_rsa
  - cp .travis/id_rsa.pub /home/travis/.ssh/id_rsa
  # 改变文件权限
  - chmod 600 ~/.ssh/id_rsa
  - chmod 600 /home/travis/.ssh/id_rsa
  # 配置 git 替换为自己的信息
  - git config --global user.name 'weizhuang'
  - git config --global user.email 1017206511@qq.com
  - export YUQUE_TOKEN=bL8r66YIhTuKqraJE8lFLcVhMIBLNaapibgAyWCc

# 安装依赖
install:
  - npm install hexo-cli -g
  - npm install

# 部署的命令
script:
  - npm run deploy  # hexo clean && hexo g -d
