# .travis.yml
language: node_js   #前端工程所以是JavaScript，编译环境是node_js
node_js:
  - '8'   #指定node版本
branchs:
  only:
  - master  #指定只有检测到master分支有变动时才执行任务

cache:
  directories:
    - node_modules

# 配置环境
before_install:
  # 改变文件权限
  - chmod 600 ~/.ssh/id_rsa
  # 配置 ssh
  - eval $(ssh-agent)
  - ssh-add ~/.ssh/id_rsa
  - cp .travis/ssh_config ~/.ssh/config
  # 配置 git 替换为自己的信息
  - git config --global user.name 'weizhuang'
  - git config --global user.email 1017206511@qq.com

# 安装依赖
install:
  - npm install hexo-cli -g
  - npm install

# 部署的命令
script:
  - npm run deploy  # hexo clean && hexo g -d
